export class Passengerdetails {
    //PassengerID
    pnrid?:any;
    passengerID?:any;
    name?:string;
    gender?:string;
    emailId?:string;
    onwardSeatNumber?:string;
    returnSeatNumber?:string;
    seatNumber?:string;
    status?:string;
    mealPreference?:string;
    seatType?:string;
    tripPrice?:number;
    returnPrice?:number;
   netPrice?:number;
   returnScheduleID?:any;
    discountPrice?:number;
    scheduleID?:any;
    discountID?:any;
    age?:number;
    isCancelled?:boolean;
}
